version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/profiles/vanilla"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/profiles/omc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/profiles/aihero"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
